// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCJpC8AC-EjSvsRLM7KPqv7H1MfoS9zHQ',
    appId: '1:843781246572:web:994a9c09c302ea4f755249',
    messagingSenderId: '843781246572',
    projectId: 'pushnotification-e614c',
    authDomain: 'pushnotification-e614c.firebaseapp.com',
    storageBucket: 'pushnotification-e614c.appspot.com',
    measurementId: 'G-643E1QGLDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEaLXx3_VX00-306tEOR5KR5EAzHMBmNA',
    appId: '1:843781246572:android:5b7c1651ac17dbaa755249',
    messagingSenderId: '843781246572',
    projectId: 'pushnotification-e614c',
    storageBucket: 'pushnotification-e614c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMHa7OqXp3jev0v6UjOEsToyiOesg3Xwc',
    appId: '1:843781246572:ios:6925eb851edc8c8d755249',
    messagingSenderId: '843781246572',
    projectId: 'pushnotification-e614c',
    storageBucket: 'pushnotification-e614c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMHa7OqXp3jev0v6UjOEsToyiOesg3Xwc',
    appId: '1:843781246572:ios:6925eb851edc8c8d755249',
    messagingSenderId: '843781246572',
    projectId: 'pushnotification-e614c',
    storageBucket: 'pushnotification-e614c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCJpC8AC-EjSvsRLM7KPqv7H1MfoS9zHQ',
    appId: '1:843781246572:web:40cdf077650cb5e7755249',
    messagingSenderId: '843781246572',
    projectId: 'pushnotification-e614c',
    authDomain: 'pushnotification-e614c.firebaseapp.com',
    storageBucket: 'pushnotification-e614c.appspot.com',
    measurementId: 'G-2PQECTGWSN',
  );
}
